name : Build
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up mavan dependncies caching 
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2- ${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-m2
      - name : Maven clean install
        run: mvn clean install
      - name : Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-application-dependency
          path: |
            target/spring-boot-application-1.0-SNAPSHOT.jar     
  test:
    needs: build
    runs-on : ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up mavan dependncies caching 
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2- ${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-m2
          
      - name : Run tests
        run: mvn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-application-dependency
      - name: Output the jar files
        run: ls
      - name: Deploy Application
        run: java -jar spring-boot-application-1.0-SNAPSHOT.jar         
  
